# Site settings
title: Ampyll
email: max@maxquattromani.com
url_slug:
description: ""
baseurl: "/ampyll"
logo: "logo.png"
version: 0.0.1
url: ""
author: "Max Quattromani"

# Build settings
jquery-version: 3.1.1

# Included Gems
gems: [jekyll-admin, jekyll-paginate]

# AMP versions of pages go in this directory
ampdir: amps

# Writing
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false

highlighter: rouge

# Use pages inside the /_pages folder
include: ["_pages"]

# When pagination is required, set intervals
paginate: 5

# remove unnecessary strings from URLs
permalink: none

# Don't include in the build
exclude: ['node_modules']

# Googles
google-verify:
google-analytics: false
google-analytics_id:
google-maps-javascript-api-key:

# Page-type Defaults
defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: "post"

-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "default"

# Phyical Attributes
map:
  address: '123 Main Street'
  city: 'Anywhere'
  state: 'CO'
  zip: '80204'
  latitude: ''
  longitude: ''

phone: '(303)555-5555'

# Socials
social:
  facebook:
  twitter:
  linkedin:
  snapchat:
  github:
  disqus:
