# Site settings
title: Placewise Media
email: info@placewise.com
url_slug: placewise
description: "PlaceWise Media is one of the nation’s largest shopper media networks and the leading provider of digital marketing services to hundreds of malls and lifestyle centers across North America."
baseurl: ""
logo: "logo.png"
version: 0.0.1
url: "http://placewise.com"
author: "Max Quattromani"

# Build settings
jquery_version: 3.1.1

# Included Gems
gems: [jekyll-admin, jekyll-paginate]

# AMP versions of pages go in this directory
ampdir: amps

# Writing
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false

highlighter: rouge

# Use pages inside the /_pages folder
include: ["_pages"]

# When pagination is required, set intervals
paginate: 5

# remove unnecessary strings from URLs
permalink: none

# Don't include in the build
exclude: ['node_modules']

# Googles
google_verify:
google_analytics: false
google_analytics_id: UA-16546876-3
google_maps_javascript_api_key:

# Page-type Defaults
defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: "post"

-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "default"

# Phyical Attributes
map:
  address: '1390 Lawrence Street #300'
  city: 'Denver'
  state: 'CO'
  zip: '80204'
  latitude: '39.746376'
  longitude: '-104.998912'

phone: '(303)296-2413'
tollfree: '(800)977-6255'

# Socials
social:
  facebook: placewise
  twitter: placewise
  linkedin: placewise-media
  snapchat: placewise
  github: PlacewiseMedia
  disqus: PlacewiseMedia
